### PR TITLE
Mypyc Build

### PR DESCRIPTION
**Pull request by Lunarmagpie**
The wheels build

Issues:
- macos arm64 wheels aren't build because of a bug with cibuildwheel. `universal2` wheels are built that work with macos arm64 but aren't fetched by arm64 errors due to a naming error.

### CODE REVIEW

**Comment by CircuitSacul** [comment]
> The version of the wheels is always 0. I am confused because i am using poetry version and the tag.

The version in pyproject is also 0. The version is set inside the build script for when it's published

**Comment by Lunarmagpie** [comment]
Manually setting the version in pyproject.toml is annoying but its not the worst ever right :skull:

**Comment by Lunarmagpie** [comment]
Everything works besides for macos arm64 wheels

**Comment by CircuitSacul** [comment]
> Everything works besides for macos arm64 wheels

does that mean arm64 users won't be able to install pycooldown?

**Comment by Lunarmagpie** [comment]
> does that mean arm64 users won't be able to install pycooldown?

They can. They will just need to build it which will take about a minute.

**Comment by CircuitSacul** [comment]
> > does that mean arm64 users won't be able to install pycooldown?
> 
> They can. They will just need to build it which should take less than a minute. Since its macos as well im pretty sure there isn't any issues with the linker or compiler out of the box.

Is building automatic when it's installed?

**Comment by Lunarmagpie** [comment]
> Is building automatic when it's installed?

Yes

**Review by CircuitSacul — APPROVED** [review]

**Pull request merged**
